name: vaahflutter
description: "Essentials for every flutter app"
version: 0.0.1
homepage: https://github.com/webreinvent/vaahflutter

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Utils
  path_provider: ^2.1.5
  package_info_plus: ^8.3.1
  json_annotation: ^4.9.0

  # Logging
  sentry_flutter: ^9.6.0
  datadog_flutter_plugin: ^2.12.0

  # Permission Manager
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

flutter:
  assets:
    - assets/
