name: vaahflutter
description: VaahFlutter, essentials for every app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2"
  flutter: ">=3.7.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  colorize: ^3.0.0
  flutter_screenutil: ^5.6.1
  dio: ^5.0.0
  fluttertoast: ^8.1.3
  get_storage: ^2.0.3
  intl: ^0.18.0
  file_picker: ^5.2.5
  font_awesome_flutter: ^10.4.0
  sentry_flutter: ^6.20.1
  firebase_dynamic_links: ^5.0.16
  firebase_core: ^2.7.1
  onesignal_flutter: ^3.5.0
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  # below line allows you use Material Icons in application
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/music/

  # To add custom fonts to your application
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700