name: vaahflutter
description: VaahFlutter, essentials for every flutter app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=3.0.3"
  flutter: ">=3.13.1"

dependencies:
  flutter:
    sdk: flutter
  # Annotations
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  # Console
  colorize: ^3.0.0
  # Log and Performance
  sentry_flutter: ^7.9.0
  # State Management
  get: ^4.6.5
  # Api
  dio: ^5.2.1+1
  # Utilities
  intl: ^0.18.1
  fluttertoast: ^8.2.2
  file_picker: ^5.3.2
  # Firebase
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  firebase_dynamic_links: ^5.3.3
  # Notifications
  onesignal_flutter: ^3.5.1
  flutter_local_notifications: ^15.1.0+1
  pusher_channels_flutter: ^2.1.2
  timezone: ^0.9.2
  # Storage
  get_storage: ^2.1.1
  # Icons
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6

flutter:
  # below line allows you use Material Icons in application
  uses-material-design: true
